# Generated by Django 4.1.3 on 2023-01-27 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_remove_producto_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='productos.categorias'),
            preserve_default=False,
        ),
    ]
