# Generated by Django 4.1.3 on 2023-01-27 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_producto_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='category',
        ),
    ]
