# Generated by Django 4.1.3 on 2023-01-27 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileuser',
            name='bio',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
