# Generated by Django 4.1.3 on 2023-01-27 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0003_alter_profileuser_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileuser',
            name='bio',
            field=models.TextField(blank=True, default='ingrese su bio', null=True),
        ),
    ]
